### ISSUE TITLE
L i v e   d e m o ?

### ISSUE THREAD

**Issue by whaaaley** [baggo/aesthetic#1]

**Comment by citrusui** [comment]
Count me in. I have my own demo setup @ <https://git.io/width>. Rather than space out the text, it converts the letters to their [CJK](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms) full width equivalents.

I have some ideas for extending this project:

- A darker theme, much easier on the eyes
- Ditch Bootstrap for something more lightweight and colorful
- Have some sort of "trending" tab on the bottom that highlights the most popular words by actual users... this will require a dynamic site powered by something like [Firebase.](https://firebase.google.com)

- And maybe change the font up to something like [System...?](https://medium.design/system-shock-6b1dc6d6596f)

**Comment by whaaaley** [comment]
👍 Dark theme
👍 Ditching bootstrap (I'd actually prefer to not use a css framework at all)
👍 Trending
👍 Fonts

Other thoughts, for the demo I was originally just going to set up a simple Vue.js app with just one component with a binded input and the styles would have just been plain scss/css.

**Comment by whaaaley** [comment]
This demo should probably go in baggo.github.io repo instead, then all the demos could use the same styles for consistency

**Comment by whaaaley** [comment]
I don't think we're going ever get around to adding a live demo.
